export const POST_TODO_SUCCESS = "POST_TODO_SUCCESS";
export const POST_TODO_REQ = "POST_TODO_REQ";
export const POST_TODO_FAILURE = "POST_TODO_FAILURE";

export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS";
export const GET_TODO_REQ = "GET_TODO_REQ";
export const GET_TODO_FAILURE = "GET_TODO_FAILURE";

export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
export const DELETE_TODO_REQ = "DELETE_TODO_REQ";
export const DELETE_TODO_FAILURE = "DELETE_TODO_FAILURE";

export const UPDATE_STATUS_TODO_SUCCESS = "UPDATE_STATUS_TODO_SUCCESS";
export const UPDATE_STATUS_TODO_REQ = "UPDATE_STATUS_TODO_REQ";
export const UPDATE_STATUS_TODO_FAILURE = "UPDATE_STATUS_TODO_FAILURE";

export const CLEAR_COMPLETED = "CLEAR_COMPLETED";
